### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by Crell** [metaleap/go-xsd#14]
I know this was mentioned in a few other already closed issues, but there's still no LICENSE file, and the README doesn't list a license.  While it's clear from the previous issues that you're fine with anyone doing anything, if there is no license actually listed it means **it is illegal for people to use this code**.  (Yes, the law is stupid at times.)  Please include a LICENSE file, whatever it is, so that people can legally use this code.

As a side note, while I appreciate the copyright flippancy behind the WTF license that actually makes it _harder_ for some people to use, as they have to get a license approved by corporate lawyers.  Generally they've already approved MIT, BSD, and other licenses that are effectively identical to the WTF license, so using WTF actually _inhibits_ reuse.  I'd recommend using MIT or BSD instead for an actual license.

(Disclaimer: I used to be Director of Legal Affairs for the Drupal project, and am helping to establish the new Drupal licensing team. I've spent a lot of time dealing with the intricacies of Open Source licensing; I'm speaking from experience and lengthy conversations with copyright attorneys, not just out of my arse.)

**Comment by lobatt** [comment]
I have been using this project and found it useful, planed to improve it while using it, however, not sure how much time I can allocate aside for other feature requests...
