### ISSUE TITLE
Create a Golang struct from an XSD

### ISSUE THREAD

**Issue by aresetian** [metaleap/go-xsd#16]
I want to create a Golang struct from an XSD (Structure XSD).

 I've read the post http://stackoverflow.com/questions/20734450/generate-go-structs-from-xsd which recommend using go-xsd,  but I have downloaded go-xsd and installed xsd-makepkg and I cannot generate my struct.

 What I am doing?

 xsd-makepkg -basepath="/Users/XSD_Access/" -goinst=false

 -xsd-makepkg: it is the binary create from apart [go-xsd-pkg](http://github.com/metaleap/go-xsd-pkg)  
 -basepath: Contains the route where I have Structure XSD that I want to transform to struct.
 -goinst : I have not installed go-buildrun and I think it is not neccesary , for that reason is ser false

What is the result of the command?

A folder($GOPATH/usr/Users/XSD_Access/) that contains other folders with all followers XML wrappers 
- docbook.org
- docs.oasis-open.org
- kbcafe.com
- khronos.org
- schemas.opengis.net
- thearchitect.co.uk
- Users
- www.w3.org

Structure XSD

```
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
   <xs:element name="Request" type="Request"/>
   <xs:complexType name="Request">
      <xs:annotation>
         <xs:documentation xml:lang="sp"><![CDATA[
        Comment xxxxx
     ]]></xs:documentation>
  </xs:annotation>
  <xs:sequence>
     <xs:element name="idOne" type="xs:string" minOccurs="0" maxOccurs="1">
      <xs:annotation>
     <xs:documentation xml:lang="sp"><![CDATA[Comment xxxxx
     ]]></xs:documentation>
      </xs:annotation>
    </xs:element>
         <xs:element name="idTwo" type="xs:string" minOccurs="0" maxOccurs="1">
  <xs:annotation>
     <xs:documentation xml:lang="sp"><![CDATA[Comment xxxxxx
     ]]></xs:documentation>
  </xs:annotation>
</xs:element>
  </xs:sequence>
   </xs:complexType>
</xs:schema>
```

Can anyone tell me what I am doing wrong or what step I missed that it does not let me create a struct from my Structure XSD?

Thanks in advance

**Comment by thiloplanz** [comment]
This has been cross-posted (and answered) at http://stackoverflow.com/questions/28052863/create-a-golang-struct-from-an-xsd

Should be closed here.
