### ISSUE TITLE
go get issue: cannot get go-forks/fsnotify

### ISSUE THREAD

**Issue by ssa21** [metaleap/go-xsd#25]
Hi, 

I am new to Go, and I was trying to clone the repo with following command

env GIT_TERMINAL_PROMPT=1 go get -u github.com/metaleap/go-xsd/xsd-makepkg

I am getting the following error:

Cloning into '$GOPATH/src/github.com/go-forks/fsnotify'...

remote: Repository not found.
fatal: repository 'https://github.com/go-forks/fsnotify/' not found
package github.com/go-forks/fsnotify: exit status 128

Not sure how to resolve this issue. Would appreciate any pointers..

Thanks...

**Comment by metaleap** [comment]
I should really find a maintainer for these old Go packages 🤣 well now that I moved numerous repos I better fix the import paths.. I'm on it

**Comment by metaleap** [comment]
Just updated outdated import paths in all these "legacy" packages.. most probably still won't even compile without numerous tweaks nowadays as the years have passed, but keeping them on for instructional/reference/nostalgic reasons of course. You're probably best-advised to look into the various forks of this particular package (then create your own in case those too go offline in the future)..

**Comment by ssa21** [comment]
Thanks..
