### ISSUE TITLE
extremely long generated names

### ISSUE THREAD

**Issue by andersfylling** [metaleap/go-xsd#35]
Here's an example: `XsdGoPkgHasElem_Harmonics5ThallTxsdHarmonicsAndFrequencyDataSequenceHarmonicsAndFrequencySequenceHarmonicsPhaseDataharmonicsPhaseDatasequenceTxsdHarmonicsAndFrequencyDataSequenceHarmonicsAndFrequencyharmonicsAndFrequencysequenceTxsdHarmonicsAndFrequencyDataharmonicsAndFrequencyDataschema_Harmonics5Th_TminMaxIntervalValue_`

Is there a way to handle this, I assume it's the namespace? (somehow)

**Comment by fanborges** [comment]
I got this issue too.

**Comment by andersfylling** [comment]
closed due to no response
